Repository adaptlearning/adapt-contrib-vanilla, pull requests merged in 2022-07, with the labels that each got.

#338 #337 Add selected underline to filter tab
  less/_defaults/_colors.less
  less/plugins/adapt-contrib-resources/resources.less
Labels: bug

#343 New: Issue and pr project addition automation (Fixes #3315)
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/workflows/addtomainproject.yml
Labels: enhancement

#336 issue/335 Add Hotgraphic styling for visited icon
  less/plugins/adapt-contrib-hotgraphic/hotgraphic.less
Labels: bug, accessibility

#334 issue/38 Moved background images into their own divs
  js/theme.js
  js/themePageView.js
  js/themeView.js
  less/core/article.less
  less/core/block.less
  less/core/page.less
  less/plugins/adapt-contrib-boxmenu/boxMenu.less
Labels: bug

#347 Fix: Added gitignore for release automation
  .gitignore
Labels: enhancement
