Repository adaptlearning/adapt-contrib-vanilla, pull requests merged in 2022-11, with the labels that each got.

#354 Update: component vertical alignment property (fixes #353)
  example.json
  js/themeBlockView.js
  less/core/block.less
  less/project/theme-extras.less
  properties.schema
  schema/block.schema.json
Labels: enhancement

#363 Fix: Firefox attribution fix (fixes #352)
  less/core/attribution.less
Labels: bug

#361 Fix: Updated readme (fixes #360)
  README.md
Labels: documentation

#368 Docs: Removed block alignment custom classes (fixes #367)
  example.json
Labels: documentation

#369 New: Add @body-background-color and apply to body element (fixes #349)
  less/_defaults/_colors.less
  less/core/global.less
Labels: enhancement

#366 Docs: Removed accordion / hotgraphic item image classes (fixes #365)
  example.json
Labels: documentation

#359 Breaking: block padding property (fixes #358)
  README.md
  bower.json
  example.json
  js/themeBlockView.js
  less/core/block.less
  less/project/theme-extras.less
  package.json
  properties.schema
  schema/block.schema.json
Labels: enhancement, breaking

#364 New: Text alignment update (fixes #362)
  README.md
  example.json
  js/theme.js
  js/themeComponentView.js
  js/themePageView.js
  js/themeView.js
  less/core/global.less
  properties.schema
  schema/article.schema.json
  schema/block.schema.json
  schema/component.schema.json
  schema/contentobject.schema.json
Labels: enhancement

#373 Fix: Added missing header-color default (fixes: #372)
  less/project/theme-extras.less
Labels: enhancement

#375 Fix: Added missing defaults for comp header bg mixin (fixes: #374)
  less/project/theme-extras.less
Labels: bug
