Repository adaptlearning/adapt-contrib-vanilla, pull requests merged in 2023-04, with the labels that each got.

#408 Fix: Added slider fill and marking styling (fixes #407)
  less/plugins/adapt-contrib-slider/slider.less
Labels: bug

#409 Replace glossary search textbox margin with padding
  less/plugins/adapt-contrib-glossary/glossary.less
Labels: bug

#405 Fix: Make align-vert-center work with block min-heights (fixes #403)
  less/core/block.less
Labels: bug, enhancement

#421 Fix: Added textinput item bottom margin (fixes #420)
  less/plugins/adapt-contrib-textInput/textinput.less
Labels: bug

#419 Fix: Remove _favicon._src default schema value (fixes #418)
  schema/course.schema.json
Labels: bug

#415 Fix: Add font size variable for nav button label (fixes #414)
  less/_defaults/_font-config.less
  less/core/nav.less
Labels: enhancement
