Repository adaptlearning/adapt-contrib-vanilla, pull requests merged in 2023-05, with the labels that each got.

#425 Fix: Add @shadow-opacity variable (fixes #424)
  less/_defaults/_colors.less
  less/core/loading.less
  less/core/shadow.less
Labels: enhancement

#429 Fix: Match columns to breakpoints
  less/project/columns.less
  package.json
Labels: bug

#423 Fix: Add new menu header color variables (fixes #402)
  less/_defaults/_colors.less
  less/plugins/adapt-contrib-boxmenu/boxMenu.less
  properties.schema
  schema/theme.schema.json
Labels: enhancement

#440 @navigation-height deprecated, added notes to avoid confusion
  less/_defaults/_spacing-containers.less
Labels: enhancement, documentation

#438 Fix: Convert the default instruction text styling from italics to bold
  less/_defaults/_font-config.less
Labels: bug, enhancement

#432 Fix: Add missing xlarge to vanilla theme
  example.json
  js/themePageView.js
  js/themeView.js
  less/_defaults/_spacing-containers.less
  properties.schema
  schema/article.schema.json
  schema/block.schema.json
  schema/contentobject.schema.json
Labels: enhancement

#445 Fix: missing schema object name in article.schema.json
  schema/article.schema.json
Labels: bug

#437 Fix: convert item and button borders from px to rem (fixes #436)
  less/_defaults/_spacing-config.less
Labels: bug
