Repository adaptlearning/adapt-contrib-vanilla, pull requests merged in 2023-07, with the labels that each got.

#448 Update: replace notify button icon duplicate styles with mixin (fixes #443)
  less/core/notify.less
  less/core/notifyPush.less
  less/plugins/adapt-contrib-hotgraphic/hotgraphicPopup.less
  less/plugins/adapt-contrib-tutor/tutor.less
Labels: enhancement

#454 Fix: Remove background color on Hot Graphic pins when using pin images (fixes #453)
  less/plugins/adapt-contrib-hotgraphic/hotgraphic.less
Labels: bug

#435 Fix: Increase container horizontal padding (gutters & margins)
  less/_defaults/_spacing-containers.less
  less/plugins/adapt-contrib-boxmenu/boxMenuItem.less
Labels: bug, enhancement

#455 Update: Hotgraphic pin number inherits from the icon styles (fixes #282)
  less/plugins/adapt-contrib-hotgraphic/hotgraphic.less
Labels: enhancement

#452 Fix: Add margins for mobile stacked layout (fixes #450)
  less/plugins/adapt-contrib-narrative/narrative.less
Labels: enhancement
